spring:
  zipkin:
    base-url: http://localhost:9411/
  config:
    import: configserver:http://localhost:9196
  application:
    name: TICKET-SERVICE
  cloud:
    config:
      uri:
        - http://localhost:9196
    
logging:
  file: 
    name: C:/Users/Zaid/Desktop/logs/microservice.log